# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 785b71249ce35d700350a4e5282270e2daac200af05fc68af16a398bcb112ee1bc726e78f85075ba8d43ae73a3acf1e25f390b4eb2bc913ce057b8119ac81661

test:
  secret_key_base: dd848767cfc513ed76ec79e6146bae49520ec7c56cb5f227bfb0f0f3182a1d6ede42ab48a26917f14d5012a1ea6582d652f40509db009cf767b0d05133080174

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
